// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {monitor} from '../models';
import {utils} from '../models';

export function ClearOldData():Promise<void>;

export function Get24HourUsage():Promise<Record<string, any>>;

export function GetDatabaseSize():Promise<number>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetHistoricalData(arg1:number):Promise<Array<database.DailySummary>>;

export function GetMonitorStatus():Promise<monitor.MonitorStatus>;

export function GetNetworkStats():Promise<Record<string, monitor.NetworkStat>>;

export function GetNetworkUsageStats():Promise<Array<database.AppUsageStat>>;

export function GetSettings():Promise<utils.Config>;

export function GetTodayStats():Promise<Record<string, any>>;

export function HideWindow():Promise<void>;

export function PauseMonitoring():Promise<void>;

export function QuitApp():Promise<void>;

export function ResumeMonitoring():Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;

export function UpdateSettings(arg1:utils.Config):Promise<void>;
