// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearOldData() {
  return window['go']['main']['App']['ClearOldData']();
}

export function Get24HourUsage() {
  return window['go']['main']['App']['Get24HourUsage']();
}

export function GetDatabaseSize() {
  return window['go']['main']['App']['GetDatabaseSize']();
}

export function GetDatabaseStats() {
  return window['go']['main']['App']['GetDatabaseStats']();
}

export function GetHistoricalData(arg1) {
  return window['go']['main']['App']['GetHistoricalData'](arg1);
}

export function GetMonitorStatus() {
  return window['go']['main']['App']['GetMonitorStatus']();
}

export function GetNetworkStats() {
  return window['go']['main']['App']['GetNetworkStats']();
}

export function GetNetworkUsageStats() {
  return window['go']['main']['App']['GetNetworkUsageStats']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTodayStats() {
  return window['go']['main']['App']['GetTodayStats']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function PauseMonitoring() {
  return window['go']['main']['App']['PauseMonitoring']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ResumeMonitoring() {
  return window['go']['main']['App']['ResumeMonitoring']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
